// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSZnfL3EuqmnmzhmEKTrbXNDCqYqv8D04',
    appId: '1:439223858386:web:62a7de06deaa29412de90b',
    messagingSenderId: '439223858386',
    projectId: 'fruit-hub-134cc',
    authDomain: 'fruit-hub-134cc.firebaseapp.com',
    storageBucket: 'fruit-hub-134cc.firebasestorage.app',
    measurementId: 'G-BE4LVDBEZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh59yPQBf5M4zSFknn_p-soEspC1FTI_M',
    appId: '1:439223858386:android:60b2bf1b83bde6ef2de90b',
    messagingSenderId: '439223858386',
    projectId: 'fruit-hub-134cc',
    storageBucket: 'fruit-hub-134cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSrT6vEZZZ68N1QtTmyWDR44q3MW6LTJ8',
    appId: '1:439223858386:ios:5f459510e3dcd18f2de90b',
    messagingSenderId: '439223858386',
    projectId: 'fruit-hub-134cc',
    storageBucket: 'fruit-hub-134cc.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSrT6vEZZZ68N1QtTmyWDR44q3MW6LTJ8',
    appId: '1:439223858386:ios:5f459510e3dcd18f2de90b',
    messagingSenderId: '439223858386',
    projectId: 'fruit-hub-134cc',
    storageBucket: 'fruit-hub-134cc.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSZnfL3EuqmnmzhmEKTrbXNDCqYqv8D04',
    appId: '1:439223858386:web:1079c6543e78c2452de90b',
    messagingSenderId: '439223858386',
    projectId: 'fruit-hub-134cc',
    authDomain: 'fruit-hub-134cc.firebaseapp.com',
    storageBucket: 'fruit-hub-134cc.firebasestorage.app',
    measurementId: 'G-4BNSM1KKW3',
  );
}
